# https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action
name: Setup Node and pnpm
inputs:
  node-version:
    required: true
    default: 18
  registry-url:
    required: true
    default: 'https://registry.npmjs.org'
  pnpm-version:
    required: true
    default: 8
  run-install:
    required: true
    default: true
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: ${{ inputs.pnpm-version }}

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: 'pnpm'

    - run: pnpm i
      shell: bash
      if: ${{ inputs.run-install == 'true' }}
