# https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action
name: Setup Node and pnpm
inputs:
  node-version:
    required: true
    default: 16
  registry-url:
    required: true
    default: 'https://registry.npmjs.org'
  pnpm-version:
    required: true
    default: 7.0.0
  run-install:
    required: true
    default: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}

    # https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time
    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - uses: pnpm/action-setup@v2.2.1
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: ${{ inputs.run-install }}
